[global]
ms_cluster_type = async+rdma        # cluster network
ms_public_type  = async+rdma        # public network
ms_async_rdma_device_name = mlx5_0  # adapt with `ibdev2netdev`
ms_async_rdma_port_num    = 1       # 1st IB port
debug ms = 1                       # prints your ldout()
